export type ToolCategory =
  | 'assistant'
  | 'code'
  | 'writing'
  | 'data'
  | 'documents'
  | 'vision'
  | 'audio'
  | 'imagegen'
  | 'knowledge'
  | 'devutils'
  | 'privacy';

export interface ToolDef {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  inputLabel: string;
  inputPlaceholder: string;
  outputLabel: string;
  systemPrompt: string;
  userPromptTemplate: string;
  inputType: 'text' | 'file' | 'custom';
  customComponent?: string;
}

export const TOOLS: ToolDef[] = [
  // ── ASSISTANT ────────────────────────────────────────
  {
    id: 'general-chat',
    name: 'AI Assistant',
    description: 'General-purpose AI chat. Ask anything.',
    category: 'assistant',
    icon: '🤖',
    inputLabel: 'Message',
    inputPlaceholder: 'Ask anything…',
    outputLabel: 'Response',
    systemPrompt: 'You are a helpful, knowledgeable assistant. Be concise and accurate.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },

  // ── CODE INTELLIGENCE ─────────────────────────────────
  {
    id: 'code-playground',
    name: 'Raw Code Zone',
    description: 'Generate, run and refine code snippets.',
    category: 'code',
    icon: '⚡',
    inputLabel: 'Describe or paste code',
    inputPlaceholder: 'e.g. Write a binary search function in TypeScript',
    outputLabel: 'Generated code',
    systemPrompt: 'You are an expert programmer. Write clean, working code with comments.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'regex-gen',
    name: 'Regex Generator & Tester',
    description: 'Describe a pattern in plain English and get a regex.',
    category: 'code',
    icon: '🔤',
    inputLabel: 'Describe the pattern',
    inputPlaceholder: 'e.g. Match email addresses but not subdomains',
    outputLabel: 'Regex + explanation',
    systemPrompt: 'You are a regex expert. Given a description, output: 1) The regex pattern 2) What it matches 3) Example matches 4) Example non-matches.',
    userPromptTemplate: 'Generate a regex for: {input}',
    inputType: 'text',
  },
  {
    id: 'sql-gen',
    name: 'SQL Generator & Explainer',
    description: 'Natural language → SQL query. Explains and optimises.',
    category: 'code',
    icon: '🗄️',
    inputLabel: 'Describe your query',
    inputPlaceholder: 'e.g. Get all users who signed up last month and have made a purchase',
    outputLabel: 'SQL + explanation',
    systemPrompt: 'You are a SQL expert. Write clean, optimised SQL queries with explanations.',
    userPromptTemplate: 'Write SQL for: {input}',
    inputType: 'text',
  },
  {
    id: 'cron-builder',
    name: 'Cron Builder',
    description: 'Plain English → cron expression with next-run preview.',
    category: 'code',
    icon: '⏰',
    inputLabel: 'Describe the schedule',
    inputPlaceholder: 'e.g. Every weekday at 9am except holidays',
    outputLabel: 'Cron expression + schedule',
    systemPrompt: 'You are a cron expert. Convert schedule descriptions to cron expressions. Show the expression, explain each field, and list the next 5 run times.',
    userPromptTemplate: 'Convert to cron: {input}',
    inputType: 'text',
  },
  {
    id: 'code-explainer',
    name: 'Code Explainer & Commenter',
    description: 'Plain-English explanation + inline comments.',
    category: 'code',
    icon: '🔍',
    inputLabel: 'Paste your code',
    inputPlaceholder: 'Paste any code here…',
    outputLabel: 'Explanation + commented code',
    systemPrompt: 'You are a senior developer explaining code to a junior. First explain what the code does in plain English, then output the same code with helpful inline comments added.',
    userPromptTemplate: 'Explain and comment this code:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'code-translator',
    name: 'Code Translator',
    description: 'Convert code between programming languages idiomatically.',
    category: 'code',
    icon: '🔄',
    inputLabel: 'Paste code (specify source and target language)',
    inputPlaceholder: 'e.g. Convert this Python to TypeScript:\n\ndef add(a, b):\n  return a + b',
    outputLabel: 'Translated code',
    systemPrompt: "You are an expert in multiple programming languages. Translate code idiomatically — use the target language's conventions, not a direct translation.",
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'test-gen',
    name: 'Unit Test Generator',
    description: 'Paste a function → get a full test suite.',
    category: 'code',
    icon: '🧪',
    inputLabel: 'Paste the function to test',
    inputPlaceholder: 'Paste your function here…',
    outputLabel: 'Test suite',
    systemPrompt: 'You are a testing expert. Write comprehensive unit tests covering: happy path, edge cases, error cases, and boundary conditions. Detect the language and use the appropriate test framework.',
    userPromptTemplate: 'Write unit tests for:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'commit-writer',
    name: 'Commit & PR Writer',
    description: 'Paste a git diff → get a commit message + PR description.',
    category: 'code',
    icon: '📝',
    inputLabel: 'Paste your git diff',
    inputPlaceholder: 'Paste git diff output here…',
    outputLabel: 'Commit message + PR description',
    systemPrompt: 'You are a developer writing commit messages. Output: 1) A Conventional Commits message (type(scope): description) 2) A PR title 3) A PR description with what changed and why.',
    userPromptTemplate: 'Write a commit message and PR description for this diff:\n\n{input}',
    inputType: 'text',
  },

  // ── WRITING ───────────────────────────────────────────
  {
    id: 'writing-tools',
    name: 'Writing Tools',
    description: 'Draft, rewrite, summarise and proofread.',
    category: 'writing',
    icon: '✍️',
    inputLabel: 'Text + instruction',
    inputPlaceholder: 'e.g. Rewrite this to be more concise:\n\n[your text]',
    outputLabel: 'Result',
    systemPrompt: 'You are a professional writer and editor. Help with drafting, rewriting, summarising, and proofreading text.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'translator',
    name: 'Offline Translator',
    description: 'Translate between 100+ languages, fully on-device.',
    category: 'writing',
    icon: '🌐',
    inputLabel: 'Text to translate (specify target language)',
    inputPlaceholder: 'e.g. Translate to French:\n\nHello, how are you?',
    outputLabel: 'Translation',
    systemPrompt: 'You are a professional translator. Provide accurate, natural-sounding translations.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'grammar-style',
    name: 'Grammar & Style',
    description: 'Fix grammar and polish writing clarity.',
    category: 'writing',
    icon: '📖',
    inputLabel: 'Paste your text',
    inputPlaceholder: 'Paste the text to fix…',
    outputLabel: 'Corrected text + changes',
    systemPrompt: 'You are a grammar and style expert. Fix all grammar, spelling, and style issues. Output the corrected text followed by a bullet list of what was changed.',
    userPromptTemplate: 'Fix grammar and style:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'tone-rewriter',
    name: 'Tone & Readability',
    description: 'Rewrite text to a target tone and reading level.',
    category: 'writing',
    icon: '🎯',
    inputLabel: 'Text + desired tone/level',
    inputPlaceholder: 'e.g. Rewrite for a 10-year-old in a friendly tone:\n\n[your text]',
    outputLabel: 'Rewritten text',
    systemPrompt: 'You are an expert at adapting text for different audiences and tones.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'email-assistant',
    name: 'Email Assistant',
    description: 'Draft, reply to, and tune emails.',
    category: 'writing',
    icon: '📧',
    inputLabel: 'Email context + instruction',
    inputPlaceholder: 'e.g. Write a polite follow-up email for a job application sent 2 weeks ago',
    outputLabel: 'Email draft',
    systemPrompt: 'You are a professional email writer. Write clear, appropriate emails for any context.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'resume-writer',
    name: 'Resume & Cover Letter',
    description: 'Tailor resume to a job, write cover letter, run ATS check.',
    category: 'writing',
    icon: '📄',
    inputLabel: 'Job description + your experience',
    inputPlaceholder: 'Paste the job description, then your current resume or skills list',
    outputLabel: 'Tailored content',
    systemPrompt: 'You are a career coach and professional resume writer. Help tailor resumes and write compelling cover letters.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'flashcards',
    name: 'Flashcards & Quiz',
    description: 'Turn notes into flashcards or a quiz.',
    category: 'writing',
    icon: '🃏',
    inputLabel: 'Paste your notes or topic',
    inputPlaceholder: 'Paste notes or describe a topic to quiz yourself on',
    outputLabel: 'Flashcards / Quiz',
    systemPrompt: 'You are an education tool. Create clear, useful flashcards or quiz questions from the provided content. Format as Q&A pairs.',
    userPromptTemplate: 'Create flashcards from:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'quick-generators',
    name: 'Quick Generators',
    description: 'Names, usernames, URL slugs, lorem ipsum — no waiting.',
    category: 'writing',
    icon: '⚡',
    inputLabel: 'Describe what to generate',
    inputPlaceholder: 'e.g. Generate 10 creative usernames for a photography app',
    outputLabel: 'Generated results',
    systemPrompt: 'You are a creative generator. Produce varied, useful results quickly.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'deck-builder',
    name: 'Deck Builder',
    description: 'Topic → editable slide deck, export as offline HTML.',
    category: 'writing',
    icon: '🎞️',
    inputLabel: 'Topic or document to turn into slides',
    inputPlaceholder: 'e.g. Create a 10-slide presentation on: The benefits of on-device AI',
    outputLabel: 'Slide deck HTML',
    systemPrompt: 'You are a presentation expert. Create clean, structured slide decks as HTML with embedded CSS. Each slide should be visually distinct with a title and key points.',
    userPromptTemplate: 'Create a slide deck for: {input}',
    inputType: 'text',
  },
  {
    id: 'markdown-studio',
    name: 'Markdown Studio',
    description: 'Write Markdown with live preview, export to HTML.',
    category: 'writing',
    icon: '📝',
    inputLabel: 'Markdown content',
    inputPlaceholder: '# My Document\n\nWrite Markdown here…',
    outputLabel: 'Preview (HTML)',
    systemPrompt: 'Convert Markdown to clean HTML. Preserve all formatting.',
    userPromptTemplate: 'Convert this Markdown to clean HTML:\n\n{input}',
    inputType: 'custom',
    customComponent: 'MarkdownStudio',
  },

  // ── DATA & SPREADSHEETS ───────────────────────────────
  {
    id: 'chat-data',
    name: 'Chat With Your Data',
    description: 'Ask plain-English questions about your spreadsheet.',
    category: 'data',
    icon: '📊',
    inputLabel: 'Paste CSV data + question',
    inputPlaceholder: 'Paste your CSV data here, then ask a question below it.\n\ne.g.\nname,age,city\nAlice,30,NYC\nBob,25,LA\n\nQuestion: Who is the oldest?',
    outputLabel: 'Answer',
    systemPrompt: 'You are a data analyst. Answer questions about tabular data accurately. Show your reasoning.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'data-cleaner',
    name: 'Data Cleaner',
    description: 'Deduplicate, trim, normalise — entirely in your browser.',
    category: 'data',
    icon: '🧹',
    inputLabel: 'Paste messy CSV or TSV data',
    inputPlaceholder: 'Paste CSV data with duplicates, bad formatting, etc.',
    outputLabel: 'Cleaned data + change summary',
    systemPrompt: 'You are a data cleaning expert. Clean the provided data: remove duplicates, trim whitespace, normalise casing, fix common formatting issues. Output the clean CSV and a summary of changes.',
    userPromptTemplate: 'Clean this data:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'format-converter',
    name: 'Format Converter',
    description: 'Convert between CSV, JSON, YAML, XML.',
    category: 'data',
    icon: '🔄',
    inputLabel: 'Paste data + specify target format',
    inputPlaceholder: 'e.g. Convert to JSON:\n\nname,age\nAlice,30\nBob,25',
    outputLabel: 'Converted data',
    systemPrompt: 'You are a data format expert. Convert data between CSV, JSON, YAML, XML, and TSV formats accurately.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'formula-gen',
    name: 'Formula Generator',
    description: 'Describe → Excel/Sheets/Airtable formula.',
    category: 'data',
    icon: '🧮',
    inputLabel: 'Describe what you need',
    inputPlaceholder: 'e.g. Sum column B where column A contains "Revenue" (Excel)',
    outputLabel: 'Formula + explanation',
    systemPrompt: 'You are a spreadsheet expert. Generate formulas for Excel, Google Sheets, or Airtable with clear explanations.',
    userPromptTemplate: 'Generate a formula for: {input}',
    inputType: 'text',
  },
  {
    id: 'data-anonymizer',
    name: 'Data Anonymizer',
    description: 'Detect and mask PII in data — fully on-device.',
    category: 'data',
    icon: '🔒',
    inputLabel: 'Paste data to anonymize',
    inputPlaceholder: 'Paste CSV or text containing personal data',
    outputLabel: 'Anonymized data',
    systemPrompt: 'You are a privacy expert. Detect and replace PII (names, emails, phones, SSNs, addresses) with realistic synthetic values. Preserve data structure.',
    userPromptTemplate: 'Anonymize this data by replacing PII with synthetic values:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'sentiment-analyzer',
    name: 'Sentiment & Theme Analyzer',
    description: 'Score sentiment and surface themes across text rows.',
    category: 'data',
    icon: '💬',
    inputLabel: 'Paste text data (one item per line or CSV)',
    inputPlaceholder: 'Paste customer reviews, feedback, or comments',
    outputLabel: 'Sentiment scores + themes',
    systemPrompt: 'You are a sentiment analysis and text mining expert. For each input, provide: sentiment (positive/negative/neutral + score 0-100), and for the full set, identify recurring themes.',
    userPromptTemplate: 'Analyse sentiment and themes in:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'chart-builder',
    name: 'Chart Builder',
    description: 'Turn data into Chart.js code, runs in preview.',
    category: 'data',
    icon: '📈',
    inputLabel: 'Paste your data + chart type',
    inputPlaceholder: 'e.g. Bar chart:\nQ1,Q2,Q3,Q4\n120,145,98,200',
    outputLabel: 'Chart HTML (copy to editor)',
    systemPrompt: 'You are a data visualisation expert. Generate complete HTML with Chart.js that creates a beautiful, responsive chart from the provided data.',
    userPromptTemplate: 'Create a Chart.js visualisation for:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'column-categorizer',
    name: 'Smart Column Categorizer',
    description: 'Tag every row into clean categories.',
    category: 'data',
    icon: '🏷️',
    inputLabel: 'Paste CSV data + category instructions',
    inputPlaceholder: 'Paste your data and describe the categories to assign',
    outputLabel: 'Categorized data',
    systemPrompt: 'You are a data categorisation expert. Tag each row with the appropriate category based on the provided criteria.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },

  // ── DOCUMENTS & PDF ───────────────────────────────────
  {
    id: 'document-assistant',
    name: 'Document Assistant',
    description: 'Summarise, explain contracts, ask questions.',
    category: 'documents',
    icon: '📋',
    inputLabel: 'Paste document text + question',
    inputPlaceholder: 'Paste document content, then ask your question',
    outputLabel: 'Summary / Answer',
    systemPrompt: 'You are a document analysis expert. Summarise documents, explain complex language in plain English, highlight risks, and answer specific questions.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'pdf-toolkit',
    name: 'PDF Toolkit',
    description: 'Merge, split, compress PDFs in your browser.',
    category: 'documents',
    icon: '📑',
    inputLabel: 'Upload PDF(s)',
    inputPlaceholder: '',
    outputLabel: 'Result PDF',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'PdfToolkit',
  },
  {
    id: 'structured-extractor',
    name: 'Structured Data Extractor',
    description: 'Pull invoices, contracts, forms into JSON/CSV.',
    category: 'documents',
    icon: '🔗',
    inputLabel: 'Paste document text + extraction schema',
    inputPlaceholder: 'e.g. Extract: vendor name, total, date, line items\n\n[paste invoice text here]',
    outputLabel: 'Extracted JSON',
    systemPrompt: 'You are a data extraction expert. Extract structured data from unstructured documents. Output valid JSON.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'receipts-csv',
    name: 'Receipts to Spreadsheet',
    description: 'Turn batch receipts/invoices into CSV.',
    category: 'documents',
    icon: '🧾',
    inputLabel: 'Paste receipt/invoice text',
    inputPlaceholder: 'Paste one or more receipts or invoices',
    outputLabel: 'CSV spreadsheet',
    systemPrompt: 'You are an accounting tool. Parse receipts and invoices and output a CSV with columns: date, vendor, description, amount, category.',
    userPromptTemplate: 'Extract receipt data as CSV:\n\n{input}',
    inputType: 'text',
  },

  // ── VISION & IMAGE ────────────────────────────────────
  {
    id: 'background-remover',
    name: 'Background Remover',
    description: 'Remove image background with RMBG-1.4, fully on-device.',
    category: 'vision',
    icon: '✂️',
    inputLabel: 'Upload image',
    inputPlaceholder: '',
    outputLabel: 'Transparent PNG',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'image-compressor',
    name: 'Smart Image Compressor',
    description: 'Shrink images to WebP/AVIF/JPEG with live size preview.',
    category: 'vision',
    icon: '🗜️',
    inputLabel: 'Upload image',
    inputPlaceholder: '',
    outputLabel: 'Compressed image',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'color-extractor',
    name: 'Color Palette Extractor',
    description: 'Pull dominant colors from any image as design tokens.',
    category: 'vision',
    icon: '🎨',
    inputLabel: 'Upload image',
    inputPlaceholder: '',
    outputLabel: 'Color palette + CSS',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'qr-barcode',
    name: 'QR & Barcode Studio',
    description: 'Generate QR codes and barcodes, or scan from image.',
    category: 'vision',
    icon: '📱',
    inputLabel: 'Text or URL to encode',
    inputPlaceholder: 'Enter URL or text to encode as QR code',
    outputLabel: 'QR Code',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'format-converter-img',
    name: 'Image Format Converter',
    description: 'Convert HEIC/JPG/PNG/WebP in batches.',
    category: 'vision',
    icon: '🖼️',
    inputLabel: 'Upload image(s)',
    inputPlaceholder: '',
    outputLabel: 'Converted image',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'favicon-gen',
    name: 'App Icon & Favicon Generator',
    description: 'One image → all favicon and PWA icon sizes.',
    category: 'vision',
    icon: '⭐',
    inputLabel: 'Upload source image',
    inputPlaceholder: '',
    outputLabel: 'ZIP of all icon sizes',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'vision-ocr',
    name: 'Vision & OCR',
    description: 'Extract text from images and photos.',
    category: 'vision',
    icon: '👁️',
    inputLabel: 'Upload image',
    inputPlaceholder: '',
    outputLabel: 'Extracted text',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },

  // ── AUDIO & VOICE ─────────────────────────────────────
  {
    id: 'audio-transcribe',
    name: 'Audio Transcription',
    description: 'Transcribe audio files using Whisper, fully on-device.',
    category: 'audio',
    icon: '🎤',
    inputLabel: 'Upload audio file',
    inputPlaceholder: '',
    outputLabel: 'Transcript',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'AudioTools',
  },
  {
    id: 'meeting-assistant',
    name: 'Meeting Assistant',
    description: 'Recording → transcript + decisions + action items.',
    category: 'audio',
    icon: '📹',
    inputLabel: 'Upload meeting recording',
    inputPlaceholder: '',
    outputLabel: 'Transcript + action items',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'AudioTools',
  },

  // ── IMAGE GENERATION ──────────────────────────────────
  {
    id: 'image-gen',
    name: 'Image Generation',
    description: 'Text → image on-device (WebGPU).',
    category: 'imagegen',
    icon: '🎨',
    inputLabel: 'Describe the image',
    inputPlaceholder: 'e.g. A futuristic city at night with neon lights',
    outputLabel: 'Generated image',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },

  // ── KNOWLEDGE & SEARCH ────────────────────────────────
  {
    id: 'chat-files',
    name: 'Chat With Your Files',
    description: 'Q&A across your uploaded documents, fully offline.',
    category: 'knowledge',
    icon: '📚',
    inputLabel: 'Upload file(s) + ask a question',
    inputPlaceholder: 'Upload a file above, then ask your question here',
    outputLabel: 'Answer',
    systemPrompt: 'You are a document Q&A tool. Answer questions accurately based ONLY on the provided document content.',
    userPromptTemplate: 'Based on this document:\n\n{input}',
    inputType: 'custom',
    customComponent: 'KnowledgeTools',
  },
  {
    id: 'auto-tagger',
    name: 'Auto-Tagger & Clusterer',
    description: 'Group notes, bookmarks, snippets into topics.',
    category: 'knowledge',
    icon: '🗂️',
    inputLabel: 'Paste items to tag (one per line)',
    inputPlaceholder: 'Paste notes, URLs, or snippets — one per line',
    outputLabel: 'Tagged + grouped items',
    systemPrompt: 'You are a knowledge organisation expert. Automatically tag and cluster the provided items into meaningful topic groups.',
    userPromptTemplate: 'Tag and cluster these items:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'duplicate-finder',
    name: 'Duplicate Finder',
    description: 'Spot near-identical passages across your files.',
    category: 'knowledge',
    icon: '🔍',
    inputLabel: 'Paste multiple text blocks (separate with ---)',
    inputPlaceholder: 'Block 1\n\n---\n\nBlock 2\n\n---\n\nBlock 3',
    outputLabel: 'Duplicate analysis',
    systemPrompt: 'You are a text analysis expert. Identify near-duplicate or very similar passages across the provided text blocks.',
    userPromptTemplate: 'Find duplicates or near-duplicates in:\n\n{input}',
    inputType: 'text',
  },

  // ── DEV UTILITIES ─────────────────────────────────────
  {
    id: 'json-tools',
    name: 'JSON & Schema Tools',
    description: 'Format, validate, diff, convert to TypeScript types.',
    category: 'devutils',
    icon: '{}',
    inputLabel: 'Paste JSON + instruction',
    inputPlaceholder: 'e.g. Convert to TypeScript types:\n\n{"name": "Alice", "age": 30}',
    outputLabel: 'Result',
    systemPrompt: 'You are a JSON expert. Format, validate, diff, convert to TypeScript interfaces, or generate JSON Schema as requested.',
    userPromptTemplate: '{input}',
    inputType: 'custom',
    customComponent: 'JsonTools',
  },
  {
    id: 'diff-viewer',
    name: 'Diff & Merge Viewer',
    description: 'Compare text, code or JSON side by side.',
    category: 'devutils',
    icon: '↔️',
    inputLabel: 'Two texts to compare',
    inputPlaceholder: 'Paste two versions of text/code separated by\n--- SEPARATOR ---',
    outputLabel: 'Diff result',
    systemPrompt: 'Compare the two provided texts and highlight all differences clearly.',
    userPromptTemplate: 'Show the differences between these two texts:\n\n{input}',
    inputType: 'custom',
    customComponent: 'DiffViewer',
  },
  {
    id: 'color-studio',
    name: 'Color & CSS Studio',
    description: 'Convert colors, WCAG contrast, build gradients.',
    category: 'devutils',
    icon: '🎨',
    inputLabel: 'Color or CSS to work with',
    inputPlaceholder: 'e.g. Convert #6d5df0 to all formats and check WCAG contrast on white',
    outputLabel: 'Color analysis + CSS',
    systemPrompt: 'You are a CSS and color expert. Convert between color formats, check WCAG contrast ratios, and generate gradients and CSS box shadows.',
    userPromptTemplate: '{input}',
    inputType: 'custom',
    customComponent: 'ColorStudio',
  },
  {
    id: 'mock-data',
    name: 'Mock Data & API Studio',
    description: 'Generate realistic fake datasets + local mock API.',
    category: 'devutils',
    icon: '🏭',
    inputLabel: 'Describe the data schema',
    inputPlaceholder: 'e.g. Generate 20 users with: name, email, age, city, subscription tier',
    outputLabel: 'Mock data (JSON/CSV)',
    systemPrompt: 'You are a mock data generator. Create realistic, varied fake data matching the described schema. Output as valid JSON array.',
    userPromptTemplate: 'Generate mock data for: {input}',
    inputType: 'text',
  },
  {
    id: 'secret-scanner',
    name: 'Secret Scanner',
    description: 'Detect leaked API keys and credentials in code.',
    category: 'devutils',
    icon: '🔑',
    inputLabel: 'Paste code or config files',
    inputPlaceholder: 'Paste code to scan for secrets…',
    outputLabel: 'Scan results',
    systemPrompt: 'You are a security expert. Scan the provided code for: API keys, tokens, passwords, private keys, connection strings, and other secrets. Report findings with line context.',
    userPromptTemplate: 'Scan for secrets and credentials in:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'accessibility-checker',
    name: 'Contrast & Accessibility',
    description: 'WCAG contrast check + color blindness preview.',
    category: 'devutils',
    icon: '♿',
    inputLabel: 'Paste HTML or color pairs to check',
    inputPlaceholder: 'e.g. Check: #6d5df0 on #08080e\nor paste HTML to audit',
    outputLabel: 'WCAG audit results',
    systemPrompt: 'You are an accessibility expert. Check WCAG 2.1 AA/AAA compliance for color contrast. Report pass/fail and suggest alternatives where needed.',
    userPromptTemplate: 'Check accessibility for: {input}',
    inputType: 'text',
  },
  {
    id: 'dev-quicktools',
    name: 'Dev Quick-Tools',
    description: 'Base64, URL encode/decode, UUID, hash, and more.',
    category: 'devutils',
    icon: '🔧',
    inputLabel: 'Input + specify operation',
    inputPlaceholder: 'e.g. Base64 encode: Hello World\nor: Generate 5 UUIDs',
    outputLabel: 'Result',
    systemPrompt: 'You are a developer utility tool. Handle: Base64 encode/decode, URL encode/decode, UUID generation, hash calculation, JSON minify/prettify, and other common dev tasks.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },

  // ── PRIVACY & SECURITY ────────────────────────────────
  {
    id: 'private-redactor',
    name: 'Private Redactor',
    description: 'Strip PII and secrets from text before sharing.',
    category: 'privacy',
    icon: '🔇',
    inputLabel: 'Paste text to redact',
    inputPlaceholder: 'Paste text containing sensitive information',
    outputLabel: 'Redacted text',
    systemPrompt: 'You are a privacy tool. Identify and redact: names, emails, phone numbers, addresses, SSNs, API keys, and other PII. Replace with [REDACTED] or descriptive placeholders.',
    userPromptTemplate: 'Redact all sensitive information from:\n\n{input}',
    inputType: 'text',
  },
  {
    id: 'password-studio',
    name: 'Password Studio',
    description: 'Generate strong passwords and audit existing ones.',
    category: 'privacy',
    icon: '🔐',
    inputLabel: 'Requirements or password to audit',
    inputPlaceholder: 'e.g. Generate a 20-char password with no ambiguous characters\nor: Audit this password: mypassword123',
    outputLabel: 'Password + strength analysis',
    systemPrompt: 'You are a password security expert. Generate strong passwords and analyse password strength with specific feedback.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'hash-checker',
    name: 'Hash & Integrity Checker',
    description: 'SHA/MD5 fingerprint + verify checksums.',
    category: 'privacy',
    icon: '#️⃣',
    inputLabel: 'Text to hash or hash to verify',
    inputPlaceholder: 'e.g. SHA-256 hash: Hello World\nor: Verify "abc123" matches [known hash]',
    outputLabel: 'Hash result',
    systemPrompt: 'You are a cryptography tool. Calculate SHA-256, SHA-512, MD5 hashes and verify checksums.',
    userPromptTemplate: '{input}',
    inputType: 'text',
  },
  {
    id: 'metadata-stripper',
    name: 'Metadata Stripper',
    description: 'Reveal hidden EXIF/GPS data in photos, then strip it.',
    category: 'privacy',
    icon: '🕵️',
    inputLabel: 'Upload image',
    inputPlaceholder: '',
    outputLabel: 'EXIF data + clean image download',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
  {
    id: 'encryption-vault',
    name: 'Encryption Vault',
    description: 'AES-256 file encrypt/decrypt in your browser.',
    category: 'privacy',
    icon: '🔏',
    inputLabel: 'File + passphrase',
    inputPlaceholder: '',
    outputLabel: 'Encrypted/decrypted file',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'EncryptionVault',
  },
  {
    id: 'steganography',
    name: 'Hidden Message in Image',
    description: 'Embed a secret message in an image or reveal one.',
    category: 'privacy',
    icon: '🖼️',
    inputLabel: 'Image + message',
    inputPlaceholder: '',
    outputLabel: 'Image with hidden message',
    systemPrompt: '',
    userPromptTemplate: '',
    inputType: 'custom',
    customComponent: 'ImageTools',
  },
];

export const CATEGORIES: { id: ToolCategory; label: string; icon: string; count: number }[] = [
  { id: 'assistant', label: 'Assistant', icon: '🤖', count: TOOLS.filter(t => t.category === 'assistant').length },
  { id: 'code', label: 'Code Intelligence', icon: '⚡', count: TOOLS.filter(t => t.category === 'code').length },
  { id: 'writing', label: 'Writing & Language', icon: '✍️', count: TOOLS.filter(t => t.category === 'writing').length },
  { id: 'data', label: 'Data & Spreadsheets', icon: '📊', count: TOOLS.filter(t => t.category === 'data').length },
  { id: 'documents', label: 'Documents & PDF', icon: '📋', count: TOOLS.filter(t => t.category === 'documents').length },
  { id: 'vision', label: 'Vision & Image', icon: '👁️', count: TOOLS.filter(t => t.category === 'vision').length },
  { id: 'audio', label: 'Audio & Voice', icon: '🎤', count: TOOLS.filter(t => t.category === 'audio').length },
  { id: 'imagegen', label: 'Image Generation', icon: '🎨', count: TOOLS.filter(t => t.category === 'imagegen').length },
  { id: 'knowledge', label: 'Knowledge & Search', icon: '📚', count: TOOLS.filter(t => t.category === 'knowledge').length },
  { id: 'devutils', label: 'Dev Utilities', icon: '🔧', count: TOOLS.filter(t => t.category === 'devutils').length },
  { id: 'privacy', label: 'Privacy & Security', icon: '🔐', count: TOOLS.filter(t => t.category === 'privacy').length },
];
